Python CV Server
smart-testing/testopithecus pull request #11
Opened 2019-05-05 15:20 UTC by psolikov

2019-05-05 18:54 UTC, amosov-f commented on testopithecus-python/src/template_matching.py
> +        return str(self.top) + " " + str(self.bottom) \
Используйте f-строки https://python-scripts.com/f-strings

2019-05-05 18:56 UTC, amosov-f commented on testopithecus-python/readme.md
> +`curl --header "Content-Type: application/json"   --header "Accept: application/json"   --request POST --data-binary  "@elements2.json" http://127.0.0.1:5000/ -i`
Лучше напишите тест через unittest

2019-05-05 18:57 UTC, amosov-f commented on testopithecus-python/src/requirements.txt
> +numpy
Этот файл должен быть в корне testopithecus-python, чтобы PyCharm его тут же подхватил

2019-05-05 18:58 UTC, amosov-f commented on testopithecus-python/src/template_matching.py
> +    return satisfies
if ...:
    return False
if ...:
    return False
return True

2019-05-05 21:06 UTC, vasyoid reviewed
Код посмотрел, запустить пока не получилось. Завтра еще попробую

2019-05-05 21:06 UTC, vasyoid commented on testopithecus-python/src/template_matching.py
> +    return satisfies
А лучше
return area_in / area_a >= 0.8 and area_in / area_b >= 0.8

2019-05-05 21:06 UTC, vasyoid commented on testopithecus-python/requirements.txt
> +cv2
Я бы еще добавил opencv-python. У меня без него не взлетело

2019-05-08 11:34 UTC, psolikov commented
У нас есть два файла "SerializationService.kt" в пакете "ru.yandex.testopithecus.utils" (один в app, другой в core), из-за чего у меня кидалось исключение "java.lang.NoSuchMethodError". Пока что я поменял пакет в core на "utilsCore". Мне кажется, нужно помержить эти файлы.

2019-05-08 14:43 UTC, vasyoid commented on core/src/main/kotlin/ru/yandex/testopithecus/stateFilter/CvClient.kt
> +        client.newCall(request).execute().use { response -> return response.body()!!.string() }
Лучше return response.body()?.string() ?: ""

2019-05-08 14:43 UTC, vasyoid commented on testopithecus-python/src/template_matching.py
> +    return [ind for ind, val in list(filter(lambda x: x[1] in matched, enumerate(elements)))]
Можно:
... for ind, _ in ...
чтобы было понятно, что val игнорируется

2019-05-08 14:56 UTC, vasyoid commented on app/src/androidTest/java/ru/yandex/testopithecus/system/AndroidElementParser.kt
> +        val base64 = Base64.encodeToString(bytes, Base64.NO_WRAP)!!
?: ""

2019-05-08 17:58 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/StateModelMonkey.kt
> +    private val filter: Filter? = if (useScreenshots) Filter(cvServerAddress!!) else null
Передавать Filter в конструкторе

2019-05-08 18:00 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/StateModelMonkey.kt
> +    private fun filterStates(uiState: UiState): UiState {
Назвать обогащением

2019-05-08 18:12 UTC, amosov-f commented on app/src/androidTest/java/ru/yandex/testopithecus/SimpleUITest.kt
> +        val monkey = AndroidMonkeyScreenshots(device, pckg, apk, context.filesDir,
Системный AndroidMonkey должен быть один 
Назовем его AndroidMonkeyRunner

2019-05-08 18:13 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/utilsCore/SerializationService.kt
> +fun serializeUiState(uiState: UiState): JSONObject {
Смержить все SerializationService и положить в core

2019-05-08 18:14 UTC, amosov-f commented on core/build.gradle
> +    implementation 'junit:junit:4.12'
убрать

2019-05-08 18:16 UTC, amosov-f requested changes
Добавить в ридми, как этим пользоваться

2019-05-13 13:59 UTC, psolikov commented
Добавил в сервер и в AndroidMonkeyScreenshots проверку живости кнопок. Еще нужно добавить код, где обрезается верхняя часть скриншота где время.

2019-05-20 13:46 UTC, psolikov commented
Пофиксил все комментарии у testopithecus-python, добавил тестов.

То что надо проверить  – как теперь выглядит AndroidMonkeyRunner, чтобы можно было мержить.

2019-05-20 23:04 UTC, vasyoid approved these changes

2019-05-21 21:14 UTC, amosov-f approved these changes

2019-05-24 17:06 UTC, merged