simple fillInput
smart-testing/testopithecus pull request #5
Opened 2019-04-19 09:29 UTC by lamertoprogrammer

2019-04-19 10:34 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +package ru.yandex.testopithecus
Давайте запихнем эти классы в более вложенный пакет

2019-04-19 10:35 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
Можно писать var top: Int, ...
Тогда не надо будет писать внизу инициализацию

2019-04-19 10:35 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +package ru.yandex.testopithecus
Вот  так и хотел, но не придумал название( Назову его rect пока

2019-04-19 10:36 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
Такие простые классы можно делать data-классами
см. data class

2019-04-19 10:37 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
У data class equals и hashCode из коробки

2019-04-19 10:39 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
Спасибо

2019-04-19 10:44 UTC, amosov-f commented on app/src/main/res/raw/config.json
> +      "fileValue": "Hi there!"
Что такое fileValue?

2019-04-19 10:45 UTC, lamertoprogrammer commented on app/src/main/res/raw/config.json
> +      "fileValue": "Hi there!"
Ой)
Это fillValue, исправлю

2019-04-19 10:46 UTC, amosov-f commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/InputFiller.kt
> +    private fun fillUnmarkedInput(unmarkedInput : UiObject2, device:UiDevice) : Boolean {
Используйте сочетание клавиш option+command+l (на маке такое) для автоматического правильного форматирования кода

2019-04-19 10:48 UTC, lamertoprogrammer commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/InputFiller.kt
> +    private fun fillUnmarkedInput(unmarkedInput : UiObject2, device:UiDevice) : Boolean {
Ок, на винде это Ctrl+Alt+I

2019-04-19 10:53 UTC, amosov-f commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/Config.kt
> +    internal var type: String = ""
Опять var, используйте val

2019-04-19 10:54 UTC, amosov-f commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/Config.kt
> +    internal var fillValue: String = ""
Должен быть массив возможных значений, который monkey может подставлять

2019-04-19 10:55 UTC, lamertoprogrammer commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/Config.kt
> +    internal var fillValue: String = ""
Да

2019-04-19 10:56 UTC, lamertoprogrammer commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/InputFiller.kt
> +object InputFiller {
Но разве так нельзя?

2019-04-19 10:56 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/RectComparison.kt
> +    fun minDistance(r1: Rectangle, r2: Rectangle): Int {
Напишите несколько юнит-тестов на этот класс

2019-04-19 10:57 UTC, lamertoprogrammer commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/Config.kt
> +    internal var fillValue: String = ""
Но я их определяю в конструкторе, а этот класс определяю как элемент списка

2019-04-19 10:58 UTC, lamertoprogrammer commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/Config.kt
> +    internal var type: String = ""
Ок

2019-04-19 11:00 UTC, lamertoprogrammer commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/Config.kt
> +    internal var type: String = ""
Только, если исправить, не корректен код конструктора

2019-04-19 11:02 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
На data класс ругается, оставил open

2019-04-19 12:10 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
Зачем нужен RectAndroid?

2019-04-19 12:12 UTC, amosov-f commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/InputFiller.kt
> +                val curDistance = RectComparison.minDistance(RectAndroid(unmarkedInput.visibleBounds),
Этот код должен быть в core и не должен зависеть от Android-а

2019-04-19 12:13 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
Для того, чтобы я без явных присваиваний передавал объект rect на сравнение алгоритму, который работает с Rectangle

2019-04-19 14:54 UTC, amosov-f commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
Не понял ничего

2019-04-19 14:58 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/Rectangle.kt
> +open class Rectangle(top: Int, left: Int, right: Int, bottom: Int) {
Ну, у нас есть объект rect, который возвращает getBounds и сравнение прямоугольников, которая работает с объектом Rectangle, чтобы упростить передачу в метод сравнения, использую этот класс

2019-04-22 21:11 UTC, lamertoprogrammer reviewed
платформонезависимое заполнение полей

2019-04-23 12:11 UTC, amosov-f commented on app/src/androidTest/java/ru/yandex/testopithecus/system/inputfiller/InputFiller.kt
> +import ru.yandex.testopithecus.RectComparison
Этот import не скомпилируется
RectComparison находится в другом пакете

2019-04-23 12:13 UTC, amosov-f reviewed
Почему у нас два InputFiller?

2019-04-23 12:13 UTC, amosov-f commented
Надо разрезолвить конфликты

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +        return UiAction(element.id, "INPUT", mapOf("text" to element.attributes["text"] as String))
Было бы лучше, если `InputFiller` просто предлагал возможные значения для текста, а не менял состояние `UiElement`. 

Это не самое ожидаемое поведение, что мы просим сгенерировать набор действий для State, а в результате он меняется

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/rect/TRectangle.kt
> +    init {
Вот это все можно заменить просто на `open class TRectangle(val top: Int, val left: Int ...)`

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/rect/TRectangle.kt
> +    override fun hashCode(): Int {
Тут было бы лучше использовать `HashBuilder` (можно посмотреть использование для `UiElement`).

Аналогично для `equals`

2019-05-01 11:55 UTC, XRater commented on app/src/androidTest/java/ru/yandex/testopithecus/system/AndroidWrapper.kt
> +class RectAndroid(rect: Rect) : TRectangle(rect.top, rect.left, rect.right, rect.bottom)
А зачем это нужно? Почему сразу `TRectangle` не сделать?

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +        return UiAction(element.id, "INPUT", mapOf("text" to element.attributes["text"] as String))
А еще, лучше сделать интерфейс вроде `InputGenerator` с методом `suggestInputs(element, state)`, а этот `InputFiller` одной из его реализаций

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +    private fun addActionsToList(actions: MutableList<UiAction>, element: UiElement, elements: List<UiElement>) {
Лучше передавать не `elements`, а сразу весь `state`

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +                input.attributes["text"] = config.fillValue
Это не компилируется, нужно сдеалть у `UiElement` мапу из атрибутов мутабельной

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +    fun fillInput(input:UiElement, allTextLabels: Collection<UiElement>) {
Много где страдает форматирование

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (config in configs) {
Было бы оптимальнее искать в обратном порядке, т.е. берем все интересующие нас атрибуты и пытаемся поискать в мапе. Пока это не очень важно, но каждый раз обходить весь конфиг может быть не быстро

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (config in configs) {
А еще от этого исчезнет дублирование кода

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (config in configs) {
Подобное дублирование встречается три раза

2019-05-01 11:55 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (markedTextView in markedTextViews) {
Вот это можно было бы красиво написать через `min` для стрима

2019-05-01 11:57 UTC, XRater commented
В целом, у меня не заработало. Для стартовой страницы почты инпут не заполняется (в конфиге текст настроил)

![image](https://user-images.githubusercontent.com/16637679/57016172-5d818280-6c21-11e9-9b5f-f2c7e32deffe.png)

2019-05-08 14:22 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +        return UiAction(element.id, "INPUT", mapOf("text" to element.attributes["text"] as String))
Сделано

2019-05-08 14:22 UTC, lamertoprogrammer commented on app/src/androidTest/java/ru/yandex/testopithecus/system/AndroidWrapper.kt
> +class RectAndroid(rect: Rect) : TRectangle(rect.top, rect.left, rect.right, rect.bottom)
Можно и без, хотелось спрятать инициализацию через класс

2019-05-08 14:22 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +    private fun addActionsToList(actions: MutableList<UiAction>, element: UiElement, elements: List<UiElement>) {
Сделано

2019-05-08 14:23 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +                input.attributes["text"] = config.fillValue
Она мутабельна

2019-05-08 14:23 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +    fun fillInput(input:UiElement, allTextLabels: Collection<UiElement>) {
Вроде бы подправил

2019-05-08 14:23 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (config in configs) {
Ищу в map

2019-05-08 14:23 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (config in configs) {
Постарался от него избавиться

2019-05-08 14:24 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (markedTextView in markedTextViews) {
Попробовал

2019-05-08 14:30 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/rect/TRectangle.kt
> +    init {
Ок

2019-05-08 14:30 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/rect/TRectangle.kt
> +    override fun hashCode(): Int {
Сделал, а почему лучше?

2019-05-14 12:07 UTC, XRater requested changes
Нужно все же добавить к коммиту все нужные файлы, иначе мне это не запустить

2019-05-14 12:07 UTC, XRater commented on app/src/androidTest/java/ru/yandex/testopithecus/system/AndroidActionPerformer.kt
> +                element.click()
А зачем мы делаем клик на элемент? Вроде нужно только текст вставить

2019-05-14 12:07 UTC, XRater commented on app/src/androidTest/java/ru/yandex/testopithecus/system/AndroidElementParser.kt
> +    private fun parseAttributes(element: UiObject2): MutableMap<String, Any> {
Можно просто `Map` вернуть, будет надежнее

2019-05-14 12:07 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +        return UiAction(element.id, "INPUT", mapOf("text" to element.attributes["text"] as String))
Все еще происходит изменение самого элемента в присваивании, этого делать не нужно. Непоустое поле `text` у элемента означает, что оно уже заполнено, на это может пологаться какоу-то другое обогощение или сама модель. 

Наша цель только сгенерить действия, так что можно просто вернуть нужное значение не меняя самой структуры

2019-05-14 12:07 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/rect/TRectangle.kt
> +    override fun hashCode(): Int {
Ну код выглядит приятнее, когда в нем все же скрыта конкретная реализация и конкретные числа (вроде 37)

2019-05-14 12:07 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +import ru.yandex.testopithecus.rect.RectComparison
Что-то плохо закоммитилось, т.к. этого класса нет

2019-05-14 12:07 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +            for (attr in nearestTextLabel.attributes.keys) {
Можно итерироваться сразу по паре, тогда не надо будет все это разворачивать внутри цикла

2019-05-14 12:07 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +                return configs[attr]?.get(input.attributes[attr])!!
Мы вроде старемся избегать !!, так что стоит написать вместо что-нибудь вроде `?: ""`

2019-05-14 12:07 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (attr in input.attributes.keys) {
Все еще этот цикл можно вынести в функцию (которая по мапе атрибутов вернет значение, которое нужно вставить)

2019-05-14 12:07 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +        actions.add(UiAction(null, "SKIP", mapOf()))
Давайте везде пользоваться одним синтаксисов, пусть все же будет `skipAction()`, `inputAction()` и прочее

2019-05-17 13:34 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/monkeys/state/actionGenerators/StateActionsGeneratorImpl.kt
> +        actions.add(UiAction(null, "SKIP", mapOf()))
Ок

2019-05-17 13:34 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +        for (attr in input.attributes.keys) {
Сделал

2019-05-17 13:34 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +                return configs[attr]?.get(input.attributes[attr])!!
Исправил

2019-05-17 13:35 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +            for (attr in nearestTextLabel.attributes.keys) {
Вызываю теперь как функцию

2019-05-17 13:35 UTC, lamertoprogrammer commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +import ru.yandex.testopithecus.rect.RectComparison
Сейчас должен быть

2019-05-23 09:22 UTC, XRater commented
Файла все еще не хватает, да и в изменениях я его не вижу

2019-05-23 09:22 UTC, XRater commented on core/src/main/kotlin/ru/yandex/testopithecus/input/InputFiller.kt
> +import ru.yandex.testopithecus.rect.RectComparison
Все еще не вижу его

2019-05-23 09:24 UTC, XRater commented
Других проблем не вижу

2019-05-24 18:29 UTC, merged